# RSL - Red Shadow Link Scarlet Demo
name: "RSL - Red Shadow Link Scarlet"
description: "Advanced Security Investigation System Demo"

# GitHub Pages basic configuration
plugins:
  - jekyll-sitemap

# Simple settings to avoid conflicts
markdown: kramdown
highlighter: rouge

# Include all files
include:
  - ".nojekyll"

# Exclude development files
exclude:
  - "server.js"
  - "start-demo.bat"
  - "package.json"
  - ".gitattributes"
  - "CNAME.example"
